### ISSUE TITLE
Gem is locked to an obsolete version of Dry::Types

### ISSUE THREAD

**Issue by jdickey** [TheProlog/prolog-dry-types#1]
As of 13 July 2016, the current version of the `dry-types` Gem is [0.8.1](https://rubygems.org/gems/dry-types/versions/0.8.1); the Gemspec for this Gem specifies that only Version [0.7.2](https://rubygems.org/gems/dry-types/versions/0.7.2) is acceptable.

This was done because, with the release of Version 0.8.0, numerous breaking changes were introduced relative to what had been done earlier.The `dry-rb` Gems were locked to specific versions that had been current when the code comprising _this_ Gem was originally written, and getting code working was judged to be more important than fiddling around with the apparently-in-flux updated versions.

This is also relevant to the [`prolog_minitest_matchers`](https://github.com/TheProlog/prolog_minitest_matchers/issues/7) Gem.

**Comment by jdickey** [comment]
This Gem can, however, be used by an application linking to a newer release of `dry-types`; however, Hilarity Ensues:

```
Error:
Prolog::UseCases::ProposeEditContribution::has a #call method that::returns a "result" object that::when called with valid parameters::includes an :article value object whose::body contains marker tag pairs for#test_0002_the ending endpoint of a Proposed Contribution:
NoMethodError: undefined method `to_i' for [92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105]:Array
Did you mean?  to_s
               to_a
               to_h
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prolog-dry_types-0.1.0/lib/prolog/dry_types/integer_range.rb:19:in `block in <module:Types>'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/constructor.rb:28:in `call'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/hash/schema.rb:51:in `block in call'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/hash/schema.rb:48:in `each'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/hash/schema.rb:48:in `each_with_object'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/hash/schema.rb:48:in `call'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/constructor.rb:28:in `call'
    /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/struct/class_interface.rb:72:in `new'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/lib/prolog/use_cases/propose_edit_contribution/update_article_with_marked_body.rb:20:in `call'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/lib/prolog/use_cases/propose_edit_contribution/update_article_with_marked_body.rb:16:in `call'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/lib/prolog/use_cases/propose_edit_contribution.rb:118:in `update_article_with_marked_body'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/lib/prolog/use_cases/propose_edit_contribution.rb:113:in `steps_in_process'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/lib/prolog/use_cases/propose_edit_contribution.rb:72:in `run_steps'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/lib/prolog/use_cases/propose_edit_contribution.rb:44:in `call'
    /Users/jeffdickey/src/rails/meldd/prolog-use_cases/test/prolog/use_cases/propose_edit_contribution_test.rb:116:in `block (4 levels) in <top (required)>'
...........
```

This appears possibly legitimate; the [line](https://github.com/TheProlog/prolog-dry-types/blob/862cbde/lib/prolog/dry/types/integer_range.rb#L19) being called out in [`integer_range.rb`](https://github.com/TheProlog/prolog-dry-types/blob/862cbde/lib/prolog/dry/types/integer_range.rb#L19) is the line immediately following the `else` in the following:

```ruby
  IntegerRange = Range.constructor do |value|
    if value.is_a?(::Range)
      value
    else
      0..value.to_i
    end
  end
```

The question is why `IntegerRange` is being called with an Array of integers when it expects either a range or a single integer. This appears to be a behavioural change between Versions 0.7.2 and 0.8.1 of the underlying [`dry-types`](https://github.com/dry-rb/dry-types) Gem. Looking at the [differences](https://github.com/dry-rb/dry-types/compare/v0.7.2...master) between 0.7.2 and current doesn't immediately point to anything revealing.

The only remaining option seems to be to allow IntegerRange to be instantiated with an Array. In this instance, we *presume* that the contents of the Array are integers, and initialise the Range with the minimum and maximum values in the Array. (We *could* do first and last instead...)

Does this make sense to anybody?

**Comment by jdickey** [comment]
Gem has been deprecated in favour of [`prolog-dry_types`](https://github.com/TheProlog/prolog-dry_types); therefore, we won't fix this here.
